### ISSUE TITLE
Holding ultimine key sometimes crashes game?

### ISSUE THREAD

**Issue by octodad484** [FTBTeam/FTB-Ultimine#33]
Pretty much the title. Playing version 1.16.3. I have the mod bound to x for now. Sometimes, the mod works normally, highlighting the correct number of blocks and breaking them when mined, but sometimes it just crashes the game instead.

**Comment by absolute-xero** [comment]
I've had the same problem but I believe I have figured it out

I've modified the config file to allow it to mine more blocks at once, the game crashes if you are looking at alot of one particular block, i.e Grass, Stone, etc. (it actually hangs I think) 

I think it's because the mod is trying to render an outline of all those blocks, and I think it's only sometimes because you end up looking at (in my case) a tree that has only so many blocks. (I've had my max_blocks line set to 2000 whiiiiich.... yeaaah.... oops)

I've set it back to something more reasonable (128) and the game hasn't crashed on me (yet)

Think for me personally, it skipped my mind cause I'm so used to using OreExcevation, Which doesn't highlight the blocks. 

Hope this helps!

**Comment by PurpleHel** [comment]
I've had a similar experience, and also concluded it was related to how many blocks the max was set to.

**Comment by MaxNeedsSnacks** [comment]
There should now be a rather clear warning in console to ***disable the block outline*** for more than 512 blocks, as vanilla shape rendering for this is *glacially* slow. Lithium makes this a lot better for more square-like shapes on Fabric (which is the loader I mainly test this mod on), so I'll be changing the warning to 256 blocks without it, and 512 with it.

**Comment by MaxNeedsSnacks** [comment]
If the amount of blocks mined is to blame for this, there's now a separate client config to set the max amount of blocks **rendered** ^^

Either way, closing this for now
