### ISSUE TITLE
Suggestion : Make the Mod more configurable.

### ISSUE THREAD

**Issue by AbiHerobrineYT** [FTBTeam/FTB-Ultimine#42]
I honestly feel like this mod is too op when mining stones, maybe make an option to configure how many blocks you can ultimine and an option to change the shape of the ultimine. ( Square, Circle, Triangle, Free-Shape, Hexagon, etc)
I would also like so that you need an item to ultimine instead of using hand to destroy stones without worrying to lose durability on your tools, and maybe make it so that when you're using ultimine the progression is slower so it feels like you're actually mining multiple blocks at once.

**Comment by DereC4** [comment]
Number of blocks can be changed now I believe

**Comment by MaxNeedsSnacks** [comment]
We've introduced max blocks and a Tag-based allow / deny lists for tools since this issue was made. The break progress thing is most likely going to be out of scope since Ultimine doesn't affect the breaking process itself, and there's already an issue for custom shapes, so I'll close this for now ^^
