### ISSUE TITLE
No outlines, scroll does nothing

### ISSUE THREAD

**Issue by LAN-Lord** [FTBTeam/FTB-Ultimine#44]
Windows 10, direwolf20 1.16.4 pack, Forge 35.1.15, running a server and connecting to it on localhost via direct connect.  I am an OP.

The mod is active, as I do get the message "FTB Ultimine is active" while holding the ` key.  When I held down shift, the second message "Hold Shift + Scroll Mouse to change shape" goes away, but nothing happens otherwise.  I pick a block, only the one block is harvested.

**Comment by LAN-Lord** [comment]
It's related to being on a server, even though it's localhost and I'm OP. It works as intended in single player.

**Comment by YWarrior99** [comment]
Me too

**Comment by Throwaway12323** [comment]
I had the same exact problem and for me it turned out I had just accidentally started the forge server by clicking the .jar application that said "Minecraft server" instead of the one that said "Forge". After I shut the server down and ran the .jar that started with "Forge" it worked on the server and for everyone who connected

**Comment by MaxNeedsSnacks** [comment]
This should no longer be an issue in newer versions
