### ISSUE TITLE
[1.16.5] Mining a Compact Ore from the mod @CompactOres drains saturation abnormally fast.

### ISSUE THREAD

**Issue by Gbergz** [FTBTeam/FTB-Ultimine#61]
When ``exhaustion_per_block`` is enabled, mine is at ``57.5`` and when you mine a Compact Ore with Ultimine enabled your saturation goes down VERY fast. Not happening on any other block.

**Mining a Compact Ore with Ultimine Enabled:**
https://user-images.githubusercontent.com/26634554/108383640-405ce000-720a-11eb-9ca1-4217121d6f6a.mp4

**Mining a Normal Ore with Ultimine Enabled:**
https://user-images.githubusercontent.com/26634554/108383708-4fdc2900-720a-11eb-971f-09be25b78998.mp4

Also note that there's no drops when Ultimining the Compact Ore, well it drops but very delayed. Pops straight into inventory later.

**Compact Ores:** 3.0.2 | Modpage: https://www.curseforge.com/minecraft/mc-mods/compact-ores
**FTB Ultimine:** 1603.1.1.13
**Minecraft:** 1.16.5
**Forge:** 36.0.25

Yes, Compact ores hasnt received an update for awhile but this this seems strange anyhow.

**-** Gbergz

**Comment by MaxNeedsSnacks** [comment]
This is pretty much exclusively on Compact Ores' end:
When a compact ore is broken, it fires multiple block break events for the base ore block it's made of (basically, it simulates the base ore being broken multiple times).

Because of this, Ultimine will also be activated multiple times for the same block, which is why the saturation goes down so ridiculously fast (basically every time the base block is broken, Ultimine adds 57.5 exhaustion). Same most likely goes for the long wait until resources are dropped as well.

This will be a pain to work around, but maybe I can come up with a solution

**Comment by Gbergz** [comment]
Ah gotcha! Thanks for the thorough explanation.

Looking forward to a possible solution. :)
**-** Gbergz

**Comment by MaxNeedsSnacks** [comment]
Just to check in again: Does this still happen in newer versions? FTB Ultimine's listener should now fire *prior* to Compact Ores' one (unless they use priority HIGHEST which I doubt), and additionally, it also shouldn't trigger when Ultimine is already active ^
