### ISSUE TITLE
[1.16] Ultimine Instantly Destroys Blocks

### ISSUE THREAD

**Issue by StygianYT** [FTBTeam/FTB-Ultimine#69]
Bug: Ultimine destroyed an 8x8 patch of grass blocks 
To Replicate: Hold bonemeal in your hand and the Ultimine key. Rapidly alternate between right and left clicking.

**Comment by MaxNeedsSnacks** [comment]
I can't reproduce this at all, all that's happening on my end is the tall grass is being destroyed over and over again

**Comment by MaxNeedsSnacks** [comment]
Ah, I see what you mean now...

This seems to be an unlucky interaction between Ultimine and an existing vanilla bug (try doing it without having ultimine activated)... I'll see what we can do about this

**Comment by MaxNeedsSnacks** [comment]
I don't think this is something we're gonna be able to fix unfortunately.
The game is saving the break progress for that grass block behind the plants (which is apparently *a feature and not a bug* in vanilla), and once that saved progress reaches 100%, it causes that block to break, triggering Ultimine as well. Since it takes so much time to do as well (you'd honestly be better off just breaking the grass in one go rather than spamming this technique) and it still takes the player's saturation away as it should, I think we're just gonna have to leave that unfixed, sorry about that
