### ISSUE TITLE
[bug]  max_blocks config not working

### ISSUE THREAD

**Issue by jonalange** [FTBTeam/FTB-Ultimine#90]
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
Slightly Vanilla Flavoured with adding this mod manually
**Forge / Fabric version, if applicable**
1.16.5 36.1.33

This is my config and the `max-block= 12` isn't working. I can still mine 64 blocks. I changed the config on the server and restarted the server multiple times.
```
#Max blocks you can mine at once
#Range: 1 ~ 32768
max_blocks = 12
#Hunger multiplied for each block mined with ultimine
#Range: 0.0 ~ 10000.0
exhaustion_per_block = 20.0
#Doesn't stop at different types of stones
merge_stone = true
#Tools that won't let you active ultimine when held
tool_blacklist = ["mininggadgets:mininggadget", "mininggadgets:mininggadget_simple", "mininggadgets:mininggadget_fancy"]
#Required for some modpacks
#Range: -1 ~ 8
render_text_manually = -1
```

**Comment by jonalange** [comment]
Found this issue which explains why it's not working.
https://github.com/FTBTeam/FTB-Ultimine/issues/74
I was changing the wrong config, but I don't have a ftbultimine.json5 file. Where is it located or where can I get it?

**Comment by MaxNeedsSnacks** [comment]
We've decided not to use json5 after all because it required an additional library (cloth-config) to be installed.

The new (and hopefully final for now) configs have been split into client (found in the "local" folder), common configs ("config"), and server configs (using forge's "serverconfig" folder inside the world folder) ^^

Unfortunately I forgot to automatically delete the old files (and implement a default config system) due to time
constraints, but this should hopefully do for now

**Comment by mortuusars** [comment]
How should I configure server config in a modpack? I placed edited ftbultimine-server.snbt in "defaultconfigs" folder, but it's not being copied to world/serverconfig.

**Comment by MaxNeedsSnacks** [comment]
See the previous comment, defaultconfigs are currently still in our TODO list unfortunately :/ I'll definitely poke around though to make sure this is done sooner rather than later

**Comment by Princeschris** [comment]
This config file is not there in fabric??
